FROM node:alpine

WORKDIR /usr/src/app

COPY . .

ENV NODE_ENV=production
RUN apk --no-cache add curl alpine-sdk python\
  && npm install\
  && addgroup -S app\
  && adduser -S app -G app\
  && chown -R app /usr/src/app\
  && chmod +x ./start-app.sh\
  && apk del alpine-sdk

# Switch to the new user
USER app

EXPOSE 3000

# Init database and start server
CMD [ "./start-app.sh" ]
